title: Mister Piksel
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 0.5787234
  lightness: 0.5483871
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#434343'
    - '#CDCDCD'
    - '#919191'
  rhythmicContrast: 0
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: Mister Piksel
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0
layout_spectrum: 1
