name: Mister Piksel
favicon: null
layout_spectrum: 0
typography_spectrum: 0
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Custom Imaging without limit
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#434343'
    - '#CDCDCD'
    - '#919191'
  brandStrength: 0.5787234
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
