name: Master Lanyard
analytics: {}
purpose:
  - type: contact
    url: 'mailto:masterlanyard@gmail.com'
    label: email us
  - type: phone
    url: 'tel:08121000339'
    label: Whatsapp 08121000339
github: true
description: Your Future Lanyard and Beyond
author:
  name: Tji Fung
  url: 'http://masterlanyard.com'
  email: tjifung@gmail.com
cta:
  bucket: null
  version: null
  domain: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.5531990480775217
navigation:
  - name: Another GREAT things
    url: 'http://juraganlanyard.com'
    type: external
color:
  lightness: 0.882971877556036
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  saturation: 0.04616011844422337
  brandStrength: 0.1223031366094578
  rhythmicContrast: 0.5869924010088353
content: []
content_rating:
  adult: false
typography_spectrum: 0.545075208476219
opengraph:
  type: Juragan Lanyard
  appId: 'https://www.facebook.com/pg/juraganlanyard/'
title: Lanyard Printing
coverPrefs:
  filter: false
