collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 0.5787234
  lightness: 1
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#434343'
    - '#CDCDCD'
    - '#919191'
  rhythmicContrast: 1
typography_spectrum: 0
layout_spectrum: 0
name: Mister Piksel
